[default_session]
ls_command = "eza --all --git --icons --color=always"

[[session]]
name = "Home ğŸ "
path = "~/"
disable_startup_command = true

[[session]]
name = "Downloads ğŸ“¥"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "Code ğŸ’»"
path = "~/Code"
startup_command = "l"

[[session]]
name = "Pictures ğŸ–¼ï¸"
path = "~/Pictures"
startup_command = "yazi"
