[default_session]
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "Home ğŸ "
path = "~/"

[[session]]
name = "Downloads ğŸ“¥"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "Code ğŸ’»"
path = "~/Code"
startup_command = "l"

[[session]]
name = "Pictures ğŸ–¼ï¸"
path = "~/Pictures"
startup_command = "yazi"

[[session]]
name = "tmux config"
path = "~/dotfiles/tmux"
startup_command = "nvim .tmux.conf"
preview_command = "bat --color=always ~/dotfiles/tmux/.tmux.conf"
